### ISSUE TITLE
Add basic structure of the Page

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#1]
- Create all minimal tags like head, body, etc.
- Integrate CDN libraries like jQuery, AJAX, Bootstrap etc.
- Create a stylish welcome message!
- Make it responsive.

**Comment by tejaswankalluri82522** [comment]
@vibrantachintya can i contribute

**Comment by BassCoder2808** [comment]
I would like to contribute on this issue.
I have created a similar web site which is a blogging site.
I have also created a repo for the same on my Github.
So I think that I will be able to do it and would like to work on it.

**Comment by alt-glitch** [comment]
@vibrantachintya I can help

**Comment by AVS18** [comment]
I would like to contribute on this.

**Comment by vibrantachintya** [comment]
Basic Structure has been merged, you can CDN links though. Also some responsive functionality will be better!
