### ISSUE TITLE
FIND FREQUENCY OF ELEMENTS IN A GIVEN ARRAY

### ISSUE THREAD

**Issue by Ananya02850** [twowaits/make-pull-request#1373]
want to work on this, please assign

**Comment by bidishaMondal7** [comment]
Interested to contribute. Please assign

**Comment by Shubham56-droid** [comment]
please assign this issue to me.

**Comment by VishalS047** [comment]
please assign me this issue. I can solve it

**Comment by Shubham56-droid** [comment]
which coding language  and folder location we are suppose to choose ?

**Comment by VishalS047** [comment]
java
