### ISSUE TITLE
Write a simple JS function to achieve below mentioned functionalities

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#17]
Write a separate function with following functionality : 

- to input a string and check whether its an email or not.
- to input a string and remove all slashes, empty spaces in beginning and end.
- to input a string and make alternative chars as lowercase and UPPERCASE. Input : Achintya Output : aChInTyA

Let me know if you have any doubts!

**Comment by faisaljamil25** [comment]
Hi @vibrantachintya I would like to do this

**Comment by krishnmohan19** [comment]
@vibrantachintya I have a doubt that Is we have to perform all three operation on a single string ..or we have to perform these operation on three different string.
