### ISSUE TITLE
Zigzag problem solution

### ISSUE THREAD

**Issue by Koushikon** [twowaits/make-pull-request#1848]
# My Program output of `Zigzag` problem

```
1                        13
  2                    12  14
    3                11      15               23
      4            10          16           22
        5        9              17       21
          6    8                  18   20      
            7                        19
```

Solved this problem but don't know how to add here so, I added to my repo:

- [Link](https://github.com/Koushikon/CPP.Programs/blob/master/Programs/Zigzag_pattern-1/Solution-1.cpp)

`Name`: Koushik

**Comment by Sakshi14-code** [comment]
Assign this issue to Me,I'll fix it.

**Comment by yashpy** [comment]
Plz assign this issue to me, I would like to code this issue.

**Comment by Koushikon** [comment]
I don't know actually how to assign this issue to someone
