### ISSUE TITLE
Add functionality to input user details

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#2]
Take input from user and display results after processing.

**Comment by iriyagupta** [comment]
@vibrantachintya A new python file with some basic problem and user input should be added?

**Comment by BassCoder2808** [comment]
Can you be somewhat more specific about what we have to do in this. Like after we take the input what we have to do with the entered data.
I would like to work on this issue.

**Comment by AVS18** [comment]
I worked on the issue and made a single pull request

**Comment by priyanshusingh0610** [comment]
Please review #22 . Resolved all conflicts, and made changes accordingly.
