### ISSUE TITLE
Write a Python program to do following

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#26]
Add a new file named - '3rdOct.py'

Add following functionalities to it :

- Take input of all the cities (5-50 any number) a traveller have visited and the date of visiting that city.
- Print the summary of the itinerary in below format.

Sample Input :  
Delhi 23/09/2019
Meerut 25/09/2019
Noida 28/09/2019
Kanpur 29/09/2019
Lucknow 1/10/2019
Delhi 1/10/2019

Sample Output : 
Traveller itinerary in 2019, he visited Delhi on 23rd Sep, Stayed for 2 days then left for Meerut on 25th Sep. Stayed for 3 days then left for Noida on 28th Sep. Stayed for 1 day then left for Kanpur on 29th Sep. Stayed for 2 days then left for Lucknow on 1st Oct. Didn't stay in Lucknow went directly to Delhi.

Try this simple program and let me know your queries in comments.

**Comment by amitm99** [comment]
Can you assign it to me. please!

**Comment by shobhitsundriyal** [comment]
can I work on it?

**Comment by Capt-Titanium** [comment]
I can work on this issue. Please clarify if you want the code to traverse a file or take input from terminal from the user.

**Comment by vibrantachintya** [comment]
@Capt-Titanium You can use any way you wish to!

**Comment by vibrantachintya** [comment]
You have time till 4 PM to submit this. If @Capt-Titanium doesn't completes by then I will assign it to someone else.

We post such problem daily in the morning 10 AM for almost all languages! You can check our other issues!

**Comment by Capt-Titanium** [comment]
Ok! Will do it right away then.

**Comment by suyash71** [comment]
hey, solved this issue. Please review and merge.
