### ISSUE TITLE
Write a JavaScript function to achieve below functionality

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#29]
Add a new file named - '3rdOct.js'

Add following functionalities to it :

- Take input of all the cities (5-50 any number) a traveller have visited and the date of visiting that city.
- Print the summary of the itinerary in below format.

**Sample Input :**

Delhi 23/09/2019
Meerut 25/09/2019
Noida 28/09/2019
Kanpur 29/09/2019
Lucknow 1/10/2019
Delhi 1/10/2019

**Sample Output :**

Traveller itinerary in 2019, he visited Delhi on 23rd Sep, Stayed for 2 days then left for Meerut on 25th Sep. Stayed for 3 days then left for Noida on 28th Sep. Stayed for 1 day then left for Kanpur on 29th Sep. Stayed for 2 days then left for Lucknow on 1st Oct. Didn't stay in Lucknow went directly to Delhi.

HINT : You can take input as just a 2D array passed as array in function parameter.

Try this simple program and let me know your queries in comments.

**Comment by MathurAditya724** [comment]
Hey, can you assign this to me? 😄

**Comment by vibrantachintya** [comment]
Assigned, make sure you submit by EOD
