### ISSUE TITLE
Design a HTML file with following functionality

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#31]
Name new file : '3rdOct.html'

Functionality : 

- Create a simple HTML form which will take sign up for Twowaits CMI program. Check form  [here](http://bit.ly/TwowaitsCMI).
- Take all the columns displayed in the above form and also all form validations as possible in the above form.
- You are free to choose any styling you wish.
- Use all the CSS, JS code within same file only. **Don't create any separate file for them, only add in 3rdOct.html**

If you have any queries let us know in comments!

**Comment by manasivaraiya** [comment]
I'd like to contribute

**Comment by ngoc199** [comment]
I'd like to make a responsive form for this task.

**Comment by shathurshan** [comment]
Hey I like to contribute

**Comment by vibrantachintya** [comment]
I have assigned it to @ngoc199, if fails to submit by 4PM, I will assign to someone else

**Comment by manasivaraiya** [comment]
ideally i should have been assigned this. right??

**Comment by vibrantachintya** [comment]
Good work @manasivaraiya, do join our Telegram group for more updates : https://t.me/joinchat/AAAAAFbbJqzUyF18Okx94A
