### ISSUE TITLE
Write a Python function to achieve below functionality

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#38]
Add a new file named - '4thOct.py'

**"ZigZag Problem"**, Add following functionalities to it :

- Take input of number of rows and columns.
- Print the following zigzag pattern.

Sample Input :
7 16

Sample Output :
<pre>
1                       13 
  2                  12  14
    3              11        15
      4          10             16
        5      9
          6  8
            7
</pre>

We will assign issues after reviewing your profile, not like if you comment first you will get automatically assigned. Do mention your college as well, we have some college specific communities.

Make sure submit by EoD.

If you need instant support join our Telegram Channel [here](https://t.me/joinchat/AAAAAFbbJqzUyF18Okx94A).

**Comment by PushpikaWan** [comment]
I would like to try this one. Can u assign this to me please

**Comment by the-brainiac** [comment]
Hello Achintya, 
Could you please assign it to me ?

**Comment by vrushti-mody** [comment]
Can I work on this?

**Comment by vibrantachintya** [comment]
OK @vrushti-mody, join our Telegrama channel http://bit.ly/TwowaitsTelegram
