### ISSUE TITLE
Write a C++ function to achieve below functionality

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#40]
Add a new file named - '4thOct.cpp'

**"ZigZag Problem"**, Add following functionalities to it :

- Take input of number of rows and columns.
- Print the following zigzag pattern.

Sample Input :
7 16

Sample Output :
<pre>
1                       13 
  2                  12  14
    3              11        15
      4          10             16
        5      9
          6  8
            7
</pre>

We will assign issues after reviewing your profile, not like if you comment first you will get automatically assigned. Do mention your college as well, we have some college specific communities.

Make sure submit by EoD.

If you need instant support join our Telegram Channel [here](https://t.me/joinchat/AAAAAFbbJqzUyF18Okx94A).

**Comment by Ashutosh-web** [comment]
Hello, @vibrantachintya I would like to take this issue. College: National Institute of Technology Jalandhar

**Comment by Ashutosh-web** [comment]
Hello, @vibrantachintya  I would like to work on this problem.
College: National Institute of Technology, Jalandhar

**Comment by Yashika25** [comment]
Hi, can I try this issue?
College Name - Amity School of Engineering and Technology (GGSIPU, Delhi).

**Comment by vibrantachintya** [comment]
Ok @Yashika25 name the file 4thOct-2.cpp

**Comment by Yashika25** [comment]
> Ok @Yashika25 name the file 4thOct-2.cpp

Okay thank you!

**Comment by bhed01** [comment]
Could you please assign it to me?
College : IERT Prayagraj
