### ISSUE TITLE
Design a HTML file with following functionality

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#41]
Add a new file named - '4thOct.html'

**"COVID Tracker"**

Create below displayed using :

![Image](https://raw.githubusercontent.com/twowaits/make-pull-request/master/4thOct-image.png)

Take static data, try to match design as close as you can to the shown image.

Use all the CSS, JS code within same file only. *Don't create any separate file for them, only add in 4thOct.html*

We will assign issues after reviewing your profile, not like if you comment first you will get automatically assigned. Do mention your college as well, we have some college specific communities.

Make sure submit by EoD.

If you need instant support join our Telegram Channel [here](https://t.me/joinchat/AAAAAFbbJqzUyF18Okx94A).

**Comment by sambatlim** [comment]
Could you assign this for me?

**Comment by sambatlim** [comment]
college: Prince of Songkla University - Thailand.

**Comment by vibrantachintya** [comment]
Ok @sambatlim, we give 1 hour for more people to apply, if no one else does. We will assign you!

**Comment by KshitijDarekar** [comment]
Hi @vibrantachintya , I would like to work on this issue.
College : Ramrao Adik Institute of Technology (Navi Mumbai,India)

**Comment by BhuvaneshPatil** [comment]
Hi I would like to contribute on this issue.
College- Sinhgad College of Engineering,Pune

**Comment by vibrantachintya** [comment]
Submit the file with 4thOct-2.html as I have already merged @sambatlim PR.

**Comment by BhuvaneshPatil** [comment]
> Submit the file with 4thOct-2.html as I have already merged @sambatlim PR.


Where?

**Comment by sambatlim** [comment]
> > Submit the file with 4thOct-2.html as I have already merged @sambatlim PR.
> 
> 
> Where?
> 

You should create 4thOct-2.html instead of 4thOct.html otherwise it will cause merge conflict.

**Comment by BhuvaneshPatil** [comment]
> > > Submit the file with 4thOct-2.html as I have already merged @sambatlim PR.
> > 
> > 
> > Where?
> 
> You should create 4thOct-2.html instead of 4thOct.html otherwise it will cause merge conflict.

Got it..!!!Thank you..!!

**Comment by Yashika25** [comment]
This issue is still open, can I start working on this?
College Name - Amity School of Engineering and Technology (GGSIPU, Delhi)

**Comment by KshitijDarekar** [comment]
@vibrantachintya with what name should I submit the file as 4thOct.html and 4thOct-2.html is taken I guess?

**Comment by vibrantachintya** [comment]
@KshitijDarekar do it with 4thOct-3.html

@Yashika25 you can submit as well

Do join our telegram channel for more updates : https://t.me/joinchat/AAAAAFbbJqzUyF18Okx94A

**Comment by Yashika25** [comment]
> @KshitijDarekar do it with 4thOct-3.html
> 
> @Yashika25 you can submit as well
> 
> Do join our telegram channel for more updates : https://t.me/joinchat/AAAAAFbbJqzUyF18Okx94A

Thanks, I'll submit it with 4thOct-4.html name as soon as its done. I've joined the telegram channel just now.

**Comment by Strigssson** [comment]
Hello, I would like to work on this issue as a school assignment.
School - Technical University of Košice, Slovakia

**Comment by ahnafhf21** [comment]
Hi, Can I contribute to this issue?

**Comment by vibrantachintya** [comment]
Time is over. Check our new issues that I am creating for 5thOct.

**Comment by Strigssson** [comment]
Hello, can I ask you to make one more issue for me ? It will be task for
mine High School subject where I need make non-trivial open-source
contribution.

Thank you.

po 5. 10. 2020 o 6:56 Achintya Gaumat <notifications@github.com> napísal(a):
