### ISSUE TITLE
Design a XML file in Android with following functionality

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#44]
Add a new file named - '4thOct.xml', only the layout file.

**"COVID Tracker"**

Create below displayed using :

![Image](https://raw.githubusercontent.com/twowaits/make-pull-request/master/Android/4thOct-android-image.png)

Take static data, try to match design as close as you can to the shown image. You may create the background as you like!

*Only push layout XML file, only add in 4thOct.xml*

We will assign issues after reviewing your profile, not like if you comment first you will get automatically assigned. Do mention your college as well, we have some college specific communities.

Make sure submit by EoD.

If you need instant support join our Telegram Channel [here](https://t.me/joinchat/AAAAAFbbJqzUyF18Okx94A).

**Comment by rahmatsyam** [comment]
Halo, can I contribute this?

**Comment by vibrantachintya** [comment]
Sure @rahmatsyam

**Comment by rahmatsyam** [comment]
oke fren

**Comment by mohdarif8299** [comment]
Can I Work on this?

**Comment by vibrantachintya** [comment]
Sure

**Comment by vibrantachintya** [comment]
Don't forget to 'star' this repo and join our Telegram group! http://bit.ly/TwowaitsTelegram

**Comment by ravigupta8006** [comment]
Sir, can you please assign this tasks to me?
college - CV Raman Global University

**Comment by Aditya489** [comment]
sir can i be assigned for this task?
college- Kalinga Institute of Industrial Technology

**Comment by yashbansal130** [comment]
please assign this to me.
college- IIT BHU

**Comment by yashbansal130** [comment]
@vibrantachintya sir can I work on this issue?
