### ISSUE TITLE
Write a function in Python to achieve below functionality

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#64]
Add a new file named - '5thOct.py'

**"Spiral Problem"**, Add following functionalities to it :

- Take input the value of 'n', upto which you will print.
- Print the following spiral pattern.

Sample Input :
25
45

Sample Output :
![](https://raw.githubusercontent.com/twowaits/make-pull-request/master/Images/5thOct-image.png)

![](https://raw.githubusercontent.com/twowaits/make-pull-request/master/Images/5thOct-image2.png)

We will assign issues after reviewing your profile, not like if you comment first you will get automatically assigned. Do mention your college as well, we have some college specific communities.

Make sure submit by EoD.

If someone has already submitted the file with name '5thOct.py', take new pull and submit another file like '5thOct-2.py', '5thOct-3.py' and so on.

If you need instant support join our Telegram Channel [here](http://bit.ly/TwowaitsTelegram).

**Comment by MathurAditya724** [comment]
Hi again @vibrantachintya, Can I work on this problem? 😀

**Comment by vibrantachintya** [comment]
Sure

**Comment by the-brainiac** [comment]
Hello @vibrantachintya ,
Could you please assign it to me ?

**Name :** Shivshanker Singh
**College :** IERT Prayagraj

**Comment by Priyanshuparihar** [comment]
Hello, @vibrantachintya ,can u assign this problem to me 
NAME : Priyanshu Parihar
COLLEGE : Jodhpur Institute of Engineering & Technology

**Comment by vibrantachintya** [comment]
This issue's time is over. You can try for next issue we will open at 11 AM.
