### ISSUE TITLE
26th Sep : Write a function in JAVA to achieve below functionality

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#647]
Add a new file named - '26thSep.java' in /Java/2021/ folder.

"Generate Binary Numbers".

Given a number n, write a function that generates and prints all binary numbers with decimal values from 1 to n.

Input: n = 2
Output: 1, 10

Input: n = 5
Output: 1, 10, 11, 100, 101

We will assign issues after reviewing your profile, not like if you comment first you will get automatically assigned. Do mention your college as well, we have some college specific communities.

Make sure submit by EoD. Do attach screenshots of output!

If someone has already submitted the file with name '26thSep.java', take new pull and submit another file like '26thSep-2.java', '26thSep-3.java' and so on.

We are creating a community of open source enthusiasts, we will be making top FOSSs in future, funded by Twowaits Technologies..

**Comment by vibrantachintya** [comment]
Sir please assign me this. I will fix it.

**Comment by PriyaRawat18** [comment]
sir please assign me this, I want to contribute to it.

**Comment by D-Palamala-Sai-Niharika** [comment]
sir please assign me this.I can fix it

**Comment by Naman-Parashar** [comment]
Assign this issue to me.

**Comment by Nikhil3389** [comment]
Sir, please assign me this, I can fix this issue

**Comment by Shivamjha12** [comment]
sir, please assign me this task! I can work on this

**Comment by Naman-Parashar** [comment]
Sir I already Make a pull request please check it.

**Comment by Harsh7Kumar** [comment]
Sir, Please assign me this task. I want to do this task. I give my best.

**Comment by yash-2k21** [comment]
PLEASE ,ASSIGN ME THIS ISSUE . I SURELY WILL FIX IT.

**Comment by anshutiwariprayagraj** [comment]
Sir, please assign me this, I can fix this issue

**Comment by anmol21mishra** [comment]
Sir i am good at java . I can fix this issue very well. Please assign this to me

**Comment by GauravMKedia** [comment]
Sir i am good in java ,I can fix this issue
