### ISSUE TITLE
26th Sep : Write a function in C++ to achieve below functionality

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#649]
Add a new file named - '26thSep.cpp' in /C++/2021/ folder.

"Generate Binary Numbers".

Given a number n, write a function that generates and prints all binary numbers with decimal values from 1 to n.

Input: n = 2
Output: 1, 10

Input: n = 5
Output: 1, 10, 11, 100, 101

We will assign issues after reviewing your profile, not like if you comment first you will get automatically assigned. Do mention your college as well, we have some college specific communities.

Make sure submit by EoD. Do attach screenshots of output!

If someone has already submitted the file with name '26thSep.cpp', take new pull and submit another file like '26thSep-2.cpp', '26thSep-3.cpp' and so on.

We are creating a community of open source enthusiasts, we will be making top FOSSs in future, funded by Twowaits Technologies..

**Comment by Meaha7** [comment]
Please Assign this issue to me

**Comment by kathan3** [comment]
assign this issue to me

**Comment by Honey-B-263** [comment]
Please assign this issue to me.

**Comment by svisen28** [comment]
Please assign this issue to me.

**Comment by suddhasattwakhan** [comment]
I am a new user and want to get the opportunity to fix the first issue.

**Comment by arya177** [comment]
Please assign this issue to me.

**Comment by Atharvp18** [comment]
Hello Sir, Please assign this issue to me.

**Comment by DhruvGarg9136** [comment]
Hello Sir, Please assign this issue to me.

**Comment by Amitlpu-840** [comment]
hi sir, please assign this task to me. I'm very experienced in c++ and can solve this issue.

**Comment by Krrishnaa25** [comment]
Please assign this task to me.

**Comment by codermittal17** [comment]
pls assign this issue to me

**Comment by codermittal17** [comment]
i will fix this issue by eod

**Comment by varsha080** [comment]
please assign this issue to me. I'm good in C++ and 4 star coder on hackkerank

**Comment by sagar1128** [comment]
please assign me i will fix it

**Comment by Umar293** [comment]
Hello Sir, Please assign this issue to me.

**Comment by codermittal17** [comment]
sir assign this issue to me

**Comment by D-Palamala-Sai-Niharika** [comment]
Sir please assign this issue.I am good at c++

**Comment by Meghna0907** [comment]
Sir please assign me this issue.

**Comment by geetika005** [comment]
Sir i am geetika bhatnagar from galgotia college of engineering and technology.Currently i am contributing to GWOC .
Kindly assign this issue to me.

**Comment by shrey714** [comment]
Hello Sir, Please assign this issue to me.

**Comment by Bharanidharan7708** [comment]
hi, can you assign this issue to me.

**Comment by ShreyashVarshney** [comment]
please assign this to me.
I want o make first contribution.
I am from GLA University.

**Comment by yash-2k21** [comment]
sir, please assign this issue to me . I will fix it .
I am from GLA University.

**Comment by Aman00702** [comment]
Sir, please assign me this problem because I am good at c++. I can solve this problem.

**Comment by Bansi-Marakana** [comment]
I can fix this issue. Please assign this issue to me

**Comment by aditi903** [comment]
Hello Sir, Please assign this issue to me.

**Comment by vibrantachintya** [comment]
@yash-2k21 @ShreyashVarshney @Bharanidharan7708 @shrey714 You can start solving this. I will accept your PR without assigning.

**Comment by ShreyashVarshney** [comment]
Sir,I already solved the issue.you can check.

**Comment by shrey714** [comment]
@vibrantachintya  Done sir

**Comment by Hrithik333** [comment]
Sir, please assign me this problem because I am good at c++. I can solve this problem.

**Comment by gb07bh** [comment]
Sir, Please assign this issue to me.

**Comment by vibrantachintya** [comment]
@gb07bh You can go ahead attempt the issue.

**Comment by varsha080** [comment]
sir please assign this task to me

**Comment by muskaan5504** [comment]
Please assign this issue to me. 
I will fix it!

**Comment by Vedika-Agrawal** [comment]
Sir plz assign this to me, I will fix it. I'm well familiar with C++.

**Comment by Rutumbhara** [comment]
Sir please assign this issue to me.
