### ISSUE TITLE
Write a function in JavaScript to achieve below functionality

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#65]
Add a new file named - '5thOct.js'

**"Spiral Problem"**, Add following functionalities to it :

- Take input the value of 'n', upto which you will print.
- Print the following spiral pattern.

Sample Input :
25
45

Sample Output :
![](https://raw.githubusercontent.com/twowaits/make-pull-request/master/Images/5thOct-image.png)

![](https://raw.githubusercontent.com/twowaits/make-pull-request/master/Images/5thOct-image2.png)

We will assign issues after reviewing your profile, not like if you comment first you will get automatically assigned. Do mention your college as well, we have some college specific communities.

Make sure submit by EoD.

If someone has already submitted the file with name '5thOct.js', take new pull and submit another file like '5thOct-2.js', '5thOct-3.js' and so on.

If you need instant support join our Telegram Channel [here](http://bit.ly/TwowaitsTelegram).

**Comment by bhed01** [comment]
Could you assign it to me?

**Comment by ishika172** [comment]
Can you please assign it to me?
Galgotias College of Engineering and Technology
