### ISSUE TITLE
26th Sep : Write a function in Python to achieve below functionality

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#650]
Add a new file named - '26thSep.py' in /Python/2021/ folder.

"Generate Binary Numbers".

Given a number n, write a function that generates and prints all binary numbers with decimal values from 1 to n.

Input: n = 2
Output: 1, 10

Input: n = 5
Output: 1, 10, 11, 100, 101

We will assign issues after reviewing your profile, not like if you comment first you will get automatically assigned. Do mention your college as well, we have some college specific communities.

Make sure submit by EoD. Do attach screenshots of output!

If someone has already submitted the file with name '26thSep.py', take new pull and submit another file like '26thSep-2.py', '26thSep-3.py' and so on.

We are creating a community of open source enthusiasts, we will be making top FOSSs in future, funded by Twowaits Technologies..

**Comment by vibrantachintya** [comment]
Assign this issue to me. I will fix it

**Comment by pranavagrawal321** [comment]
Please assign me this issue.

**Comment by nikhil05-code** [comment]
Assign it to me. I will fix it.

**Comment by kathan3** [comment]
assign this issue to me

**Comment by MananDudhwala** [comment]
Kindly assign the above issue to me. I will fix it before EoD.

**Comment by ShreyashVarshney** [comment]
sir, please assign the issue to me.
I am from GLA University

**Comment by Atijian** [comment]
please assign this issue to me 
I'm from Vit (Vellore)University

**Comment by yash-2k21** [comment]
please assign this issue , I will fix it.
I am from GLA University

**Comment by RESHU-05** [comment]
Please assign this issue to me , I will fix it.
I am from ABESEC

**Comment by Priyanshi-S** [comment]
Please assign this issue to me , I will fix it.
I am from ABESEC

**Comment by gb07bh** [comment]
Sir, Please assign me this issue. I would love to fix it.

**Comment by RK-droid** [comment]
Sir, Please Assign this issue to me as I have experience with this issue .

**Comment by RK-droid** [comment]
Sir, Please Assign this issue to me as I have experience with this issue and I am from Jaypee Institute of Information Technology

**Comment by IshaSah** [comment]
Please assign this issue to me. I'll fix it

**Comment by SahilSatyam** [comment]
Sir, assign this issue to me. I will fix it.

**Comment by SnehuD** [comment]
> Add a new file named - '26thSep.py' in /Python/2021/ folder.
> 
> "Generate Binary Numbers".
> 
> Given a number n, write a function that generates and prints all binary numbers with decimal values from 1 to n.
> 
> Input: n = 2 Output: 1, 10
> 
> Input: n = 5 Output: 1, 10, 11, 100, 101
> 
> We will assign issues after reviewing your profile, not like if you comment first you will get automatically assigned. Do mention your college as well, we have some college specific communities.
> 
> Make sure submit by EoD. Do attach screenshots of output!
> 
> If someone has already submitted the file with name '26thSep.py', take new pull and submit another file like '26thSep-2.py', '26thSep-3.py' and so on.
> 
> We are creating a community of open source enthusiasts, we will be making top FOSSs in future, funded 
Assign this issue to me. I will fix it

> Add a new file named - '26thSep.py' in /Python/2021/ folder.
> 
> "Generate Binary Numbers".
> 
> Given a number n, write a function that generates and prints all binary numbers with decimal values from 1 to n.
> 
> Input: n = 2 Output: 1, 10
> 
> Input: n = 5 Output: 1, 10, 11, 100, 101
> 
> We will assign issues after reviewing your profile, not like if you comment first you will get automatically assigned. Do mention your college as well, we have some college specific communities.
> 
> Make sure submit by EoD. Do attach screenshots of output!
> 
> If someone has already submitted the file with name '26thSep.py', take new pull and submit another file like '26thSep-2.py', '26thSep-3.py' and so on.
> 
> We are creating a community of open source enthusiasts, we will be making top FOSSs in future, funded by Twowaits Technologies..

Please Assign this issue to me. I will fix it

**Comment by SnehuD** [comment]
Assign this issue to me. I will fix it
