### ISSUE TITLE
Update the readme document

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#651]
Our current readme doc is made for Hacktoberfest 2020, kindly update it with relevant info for 2021 contest.

**Comment by vibrantachintya** [comment]
Kindly assign this issue to me. My english is good, I will put my efforts and do it within deadline.

**Comment by Naman-Parashar** [comment]
Sir please assign this to me,I am good in English,I can do this.

**Comment by varsha080** [comment]
Kindly assign me this work.

**Comment by Bharanidharan7708** [comment]
Hi, can you assign me this issue.
