### ISSUE TITLE
26th Sep Design a HTML file with following functionality

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#653]
Add a new file named - '26thSep.html' in /HTML CSS/2021/ folder.

"COVID Tracker"

Create below displayed using :

![image](https://raw.githubusercontent.com/twowaits/make-pull-request/master/4thOct-image.png)

Take static data, try to match design as close as you can to the shown image.

Use all the CSS, JS code within same file only. Don't create any separate file for them.

If someone has already submitted the file with name '26thSep.html', take new pull and submit another file like '26thSep-2.html', '26thSep-3.html' and so on.

We will assign issues after reviewing your profile, not like if you comment first you will get automatically assigned. Do mention your college as well, we have some college specific communities.

Make sure submit by EoD.

**Comment by tanishabisht** [comment]
Hello Sir,
I would like to work on this issue. Could you assign this issue to me.

**Comment by InnocentDaksh63** [comment]
Hey 👋 I would like to work on this issue. Can you assign me for this

**Comment by D-Palamala-Sai-Niharika** [comment]
Please assign this issue.I can solve this issue

**Comment by ShreyashVarshney** [comment]
please assign the issue to me. I would work on this issue
