### ISSUE TITLE
Design a HTML File with following functionality

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#67]
Add a new file named - '5thOct.html'

**"LinkedIn Profile"**

Create below displayed design :

![Image](https://raw.githubusercontent.com/twowaits/make-pull-request/master/Images/5thOct-image3.png)

For images and color refer [this linkedin profile](https://www.linkedin.com/in/achintya-gaumat-b6569365/). Take static data, try to match design as close as you can to the shown image.

Use all the CSS, JS code within same file only. *Don't create any separate file for them, only add in 5thOct.html*

We will assign issues after reviewing your profile, not like if you comment first you will get automatically assigned. Do mention your college as well, we have some college specific communities.

Make sure submit by EoD.

If someone has already submitted the file with name '5thOct.html', take new pull and submit another file like '5thOct-2.html', '5thOct-3.html' and so on.

If you need instant support join our Telegram Channel [here](http://bit.ly/TwowaitsTelegram).

**Comment by nitinshukla413** [comment]
can you please assign this task to me?

**Comment by ishika172** [comment]
can you please assign this to me?

**Comment by bhed01** [comment]
Please assign this to me.

**Comment by KeshriAyushi22** [comment]
Can you assign this to me?
Also, we need to create that functionality or just the design? Functionality like uploading the pics , changing the info

**Comment by vibrantachintya** [comment]
Just design

**Comment by chetna5404** [comment]
Assign this to me

**Comment by Yashika25** [comment]
Can I work on this issue, please?

**Comment by Geeky-star** [comment]
can I work on this issue?

**Comment by vibrantachintya** [comment]
Yes. You have time till 11 AM to submit

**Comment by chetna5404** [comment]
Hello sir,
I could not submit assigned work till 11am today because  Today is my exam
till 12:30p.m.
Kindly give me some more time to submit it

**Comment by vibrantachintya** [comment]
Don't forget to 'star' this repo and join our Telegram group! http://bit.ly/TwowaitsTelegram
