### ISSUE TITLE
29th Sep : Write a Function in JAVA to achieve below functionality

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#707]
THIS IS A DEMO ISSUE FOR HACKTOBERFEST. PR raised for this will not be counted in Hacktoberfest, you may particpate for practice.

## "Sorting an Array"

Add following functionalities to it :

- Given an array A[] consisting 0s, 1s and 2s. The task is to write a function that sorts the given array. The functions should put all 0s first, then all 1s and all 2s in last.
- You have to do it in only 1 pass, you cannot use additional space (like array) and you can't use sorting/sorting functions.

Sample Input :
{0, 1, 2, 0, 1, 2}
{0, 1, 1, 0, 1, 2, 1, 2, 0, 0, 0, 1}

Sample Output :
{0, 0, 1, 1, 2, 2}
{0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2}

- No need to wait for getting assigned, you can go ahead attempt the issues and raise a PR by 10 AM 30th Sep.
- We will review any comments or PRs at 5 PM & 10 PM on 29th Sep, will give feedback if needed.

How to name your file?
- Go to folder : "/JAVA/2021/"
- Take today's date, i.e. 29thSep
- Take your GitHUB username id like "hrithik339", "hacker-boy", etc or anything which you have.
- File extension = ".java" in this issue.

Combine all 3 to get your file name : Date + "_" + Username + File Extension, ex. "26thSep_hrithik339.java". Create this file in above mentioned folder only "/JAVA/2021/".

This will ensure no file will be conflict and any number of contributors can work on the same issue.

If you have any query ask in comments below, kindly follow this pattern strictly.

You can join our Whatsapp group to get instant support : [Link to Whatsapp Group](https://chat.whatsapp.com/H0Hn3m1sgKHKeJdoCSb74A)

**Comment by VISHAL-143x** [comment]
I want to work on this issue

**Comment by bpolaswar** [comment]
I want to work on this issue

**Comment by srijan-singh** [comment]
Sir, please assign me this issue. I've earned 4 stars in Java from Hackerrank and I'm quite confident that I'm able to solve it.
I would request you to please assign me it.
