### ISSUE TITLE
29th Sep : Make any 1 Web Page out of this Portfolio Website

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/make-pull-request#710]
THIS IS A DEMO ISSUE FOR HACKTOBERFEST. PR raised for this will not be counted in Hacktoberfest, you may particpate for practice.

## Portfolio Website

Today we will be making this portfolio website, there are 6 pages in it. You have to make only 1 page out of these 6. You can make any one of your choice

Page 1 : home.html

![](https://raw.githubusercontent.com/twowaits/make-pull-request/master/Images/29thSep_home.png)

Page 2 : about.html

![](https://raw.githubusercontent.com/twowaits/make-pull-request/master/Images/29thSep_about.png)

Page 3 : interests.html

![](https://raw.githubusercontent.com/twowaits/make-pull-request/master/Images/29thSep_interests.png)

Page 4 : skills.html

![](https://raw.githubusercontent.com/twowaits/make-pull-request/master/Images/29thSep_skills.png)

Page 5 : projects.html

![](https://raw.githubusercontent.com/twowaits/make-pull-request/master/Images/29thSep_projects.png)

Page 6 : contact.html

![](https://raw.githubusercontent.com/twowaits/make-pull-request/master/Images/29thSep_contact.png)

Rules :
- You have to choose any one page out of it and work on it.
- Write all your CSS in the same HTML file. You can either write in <style> tag or inline CSS.
- No need to wait for getting assigned, you can go ahead attempt the issues and raise a PR by 10 AM 30th Sep.
- We will review any comments or PRs at 5 PM & 10 PM on 29th Sep, will give feedback if needed.

How to name your file?
- Go to folder : "/HTML CSS/2021/"
- Take File's name, i.e. about.
- Take your GitHUB username id like "hrithik339", "hacker-boy", etc or anything which you have.
- File extension = ".html" in this issue.

Combine all 3 to get your file name : Page Name + "_" + Username + File Extension, ex. "about_hrithik339.html". Create this file in above mentioned folder only "/HTML CSS/2021/".

This will ensure no file will be conflict and any number of contributors can work on the same issue.

If you have any query ask in comments below, kindly follow this pattern strictly.

You can join our Whatsapp group to get instant support : [Link to Whatsapp Group](https://chat.whatsapp.com/H0Hn3m1sgKHKeJdoCSb74A)

**Comment by prathamesh3707** [comment]
The PR  which we will be raising by 10 AM 30th Sep will just be for practise and will not be considered in the fest right?
